import React from 'react'
import { nanoid } from 'nanoid'

export default {
    "data": {
        "boardSpaces":[
            {
                id:nanoid(),
                space: 1,
                img: "./goicon.png",
                collect: 200
            },
            {
                id:nanoid(),
                space: 2,
                name:'Mediterranian Ave',
                color:'#955436',
                value: 60,
                houseCost: 50,
                hotelCost: 50,
                mortgage: 30,
                unMortgage: 33,
                isOwned: false,
                isMortgaged: false,
                houses: 0,
                hotels: 0
            },
            {
                id:nanoid(),
                space: 3,
                name:'Community Chest',
                img: './communitychest.png'
            },
            {
                id:nanoid(),
                space: 4,
                name:'Baltic Avenue',
                color:'#955436',
                value: 60,
                houseCost: 50,
                hotelCost: 50,
                mortgage: 30,
                unMortgage: 33,
                isOwned: false,
                isMortgaged: false,
                houses: 0,
                hotels: 0
            },
            {
                id:nanoid(),
                space: 5,
                name:'Income Tax'
            },
            {
                id:nanoid(),
                space: 6,
                name:'Reading RailRoad',
                value: 200,
                mortgage: 100,
                unMortgage: 110,
                isOwned: false,
                isMortgaged: false,
            },

            {
                id:nanoid(),
                space: 7,
                name:' Oriental Avenue',
                color:'#AEE0FA',
                value: 100,
                houseCost: 50,
                hotelCost: 50,
                mortgage: 50,
                unMortgage: 55,
                isOwned: false,
                isMortgaged: false,
                houses: 0,
                hotels: 0
            },
            {
                id:nanoid(),
                space: 8,
                name:'Chance',
                img: './chance.png'
            },
            {
                id:nanoid(),
                space: 9,
                name:'Vermont Avenue',
                color:'#AEE0FA',
                value: 100,
                houseCost: 50,
                hotelCost: 50,
                mortgage: 50,
                unMortgage: 55,
                isOwned: false,
                isMortgaged: false,
                houses: 0,
                hotels: 0
            },
            {
                id:nanoid(),
                space: 10,
                name:'Connecticut Avenue',
                color:'#AEE0FA',
                value: 120,
                houseCost: 50,
                hotelCost: 50,
                mortgage: 60,
                unMortgage: 66,
                isOwned: false,
                isMortgaged: false,
                houses: 0,
                hotels: 0
            },
            {
                id:nanoid(),
                space: 11,
                inJail:false,
                justVisiting:true
            },
            {
                id:nanoid(),
                space: 12,
                name:'ST. Charles Place',
                color:'#D93A96',
                value: 140,
                houseCost: 100,
                hotelCost: 100,
                mortgage: 70,
                unMortgage: 77,
                isOwned: false,
                isMortgaged: false,
                houses: 0,
                hotels: 0
            },
            {
                id:nanoid(),
                space: 13,
                name:'Electric Company',
                value: 150,
                mortgage: 75,
                unMortgage: 83,
                isOwned: false,
                isMortgaged: false
            },
            {
                id:nanoid(),
                space: 14,
                name:'States Avenue',
                color:'#D93A96',
                value: 140,
                houseCost: 100,
                hotelCost: 100,
                mortgage: 70,
                unMortgage: 77,
                isOwned: false,
                isMortgaged: false,
                houses: 0,
                hotels: 0
            },
            {
                id:nanoid(),
                space: 15,
                name:'Virginia Avenue',
                color:'#D93A96',
                value: 160,
                houseCost: 100,
                hotelCost: 100,
                mortgage: 70,
                unMortgage: 77,
                isOwned: false,
                isMortgaged: false,
                houses: 0,
                hotels: 0
            },
            {
                id:nanoid(),
                space: 16,
                name:'Pennsylvania Railroad',
                value: 200,
                mortgage: 100,
                unMortgage: 110,
                isOwned: false,
                isMortgaged: false,
            },
            {
                id:nanoid(),
                space: 17,
                name:'St. James Place',
                color: '#F7941D',
                value: 180,
                houseCost: 100,
                hotelCost: 100,
                mortgage: 90,
                unMortgage: 99,
                isOwned: false,
                isMortgaged: false,
            },
            {
                id:nanoid(),
                space: 18,
                name:'Community Chest',
                img: './communitychest.png'
            },
            {
                id:nanoid(),
                space: 19,
                name:'Tennessee Avenue',
                value: 180,
                color: '#F7941D',
                houseCost: 100,
                hotelCost: 100,
                mortgage: 90,
                unMortgage: 99,
                isOwned: false,
                isMortgaged: false,
            },
            {
                id:nanoid(),
                space: 20,
                name:'New York Avenue',
                value: 200,
                color: '#F7941D',
                houseCost: 100,
                hotelCost: 100,
                mortgage: 100,
                unMortgage: 110,
                isOwned: false,
                isMortgaged: false,
            },
            {
                id:nanoid(),
                space: 21,
                name:'Free Parking',
                img: './freeparking.png'
            },
            {
                id:nanoid(),
                space: 22,
                name:'Kentucky Avenue',
                value: 220,
                color: '#ED1B24',
                houseCost: 150,
                hotelCost: 150,
                mortgage: 110,
                unMortgage: 121,
                isOwned: false,
                isMortgaged: false,
            },
            {
                id:nanoid(),
                space: 23,
                name:'Chance',
                img: './chance2.png'
            },
            {
                id:nanoid(),
                space: 24,
                name:'Indiana Avenue',
                value: 220,
                color: '#ED1B24',
                houseCost: 150,
                hotelCost: 150,
                mortgage: 110,
                unMortgage: 121,
                isOwned: false,
                isMortgaged: false,
            },
            {
                id:nanoid(),
                space: 25,
                name:'Illinois Avenue',
                value: 240,
                color: '#ED1B24',
                houseCost: 150,
                hotelCost: 150,
                mortgage: 120,
                unMortgage: 132,
                isOwned: false,
                isMortgaged: false,
            },
            {
                id:nanoid(),
                space: 26,
                name:'B&B RailRoad',
                value: 200,
                mortgage: 100,
                unMortgage: 110,
                isOwned: false,
                isMortgaged: false,
            },

            {
                id:nanoid(),
                space: 27,
                name:'Atlantic Avenue',
                value: 260,
                color: '#FEF200',
                houseCost: 150,
                hotelCost: 150,
                mortgage: 130,
                unMortgage: 143,
                isOwned: false,
                isMortgaged: false,
            },
            {
                id:nanoid(),
                space: 28,
                name:'Ventnor Avenue',
                value: 260,
                color: '#FEF200',
                houseCost: 150,
                hotelCost: 150,
                mortgage: 130,
                unMortgage: 143,
                isOwned: false,
                isMortgaged: false,
            },
            {
                id:nanoid(),
                space: 29,
                name:'Water Works',
                value: 150,
                mortgage: 75,
                unMortgage: 83,
                isOwned: false,
                isMortgaged: false,
            },
            {
                id:nanoid(),
                space: 30,
                name:'Marvin Gardens',
                value: 280,
                color: '#FEF200',
                houseCost: 150,
                hotelCost: 150,
                mortgage: 140,
                unMortgage: 154,
                isOwned: false,
                isMortgaged: false,
            },
            {
                id:nanoid(),
                space: 31,
                name:'Go To Jail',
            },
            {
                id:nanoid(),
                space: 32,
                name:'Pacific Avenue',
                value: 300,
                color: '#1FB25A',
                houseCost: 200,
                hotelCost: 200,
                mortgage: 150,
                unMortgage: 165,
                isOwned: false,
                isMortgaged: false,
            },
            {
                id:nanoid(),
                space: 33,
                name:'North Carolina Avenue',
                value: 300,
                color: '#1FB25A',
                houseCost: 200,
                hotelCost: 200,
                mortgage: 150,
                unMortgage: 165,
                isOwned: false,
                isMortgaged: false,
            },
            {
                id:nanoid(),
                space: 34,
                name:'Community Chest',
                img: './communitychest.png'
            },
            {
                id:nanoid(),
                space: 35,
                name:'Pennsylvania Avenue',
                value: 320,
                color: '#1FB25A',
                houseCost: 200,
                hotelCost: 200,
                mortgage: 150,
                unMortgage: 165,
                isOwned: false,
                isMortgaged: false,
            },
            {
                id:nanoid(),
                space: 36,
                name:'ShortLine RailRoad',
                value: 200,
                mortgage: 100,
                unMortgage: 110,
                isOwned: false,
                isMortgaged: false,
            },
            {
                id:nanoid(),
                space: 37,
                name:'Chance3',
                img: './chance3.png'
            },

            {
                id:nanoid(),
                space: 38,
                name:'Park Place',
                value: 350,
                color: '#0072BB',
                houseCost: 200,
                hotelCost: 200,
                mortgage: 175,
                unMortgage: 193,
                isOwned: false,
                isMortgaged: false,
            },

            {
                id:nanoid(),
                space: 39,
                name:'Luxury Tax',
                Pay: 100,
            },
            {
                id:nanoid(),
                space: 40,
                name:'Board Walk',
                value: 400,
                color: '#0072BB',
                houseCost: 200,
                hotelCost: 200,
                mortgage: 200,
                unMortgage: 220,
                isOwned: false,
                isMortgaged: false,
            }

        ],

        "gameCharacters":[
            {
                id:nanoid(),
                name:"racecar",
                isChosen:false,
                turn:false,
                money:1550,
                boardSpace: 1,
                property: [],
                isBankrupt: false,
                isInJail: false,
            },
            {
                id:nanoid(),
                name:"duck",
                isChosen:false,
                turn:false,
                money:1550,
                boardSpace: 1,
                property: [],
                isBankrupt: false,
                isInJail: false,
            },
            {
                id:nanoid(),
                name:"penguin",
                isChosen:false,
                turn:false,
                money:1550,
                boardSpace: 1,
                property: [],
                isBankrupt: false,
                isInJail: false,
            },
            {
                id:nanoid(),
                name:"dinosaur",
                isChosen:false,
                turn:false,
                money:1550,
                boardSpace: 1,
                property: [],
                isBankrupt: false,
                isInJail: false,
            },
            {
                id:nanoid(),
                name:"thimble",
                isChosen:false,
                turn:false,
                money:1550,
                boardSpace: 1,
                property: [],
                isBankrupt: false,
                isInJail: false,
            },
            {
                id:nanoid(),
                name:"tophat",
                isChosen:false,
                turn:false,
                money:1550,
                boardSpace: 1,
                property: [],
                isBankrupt: false,
                isInJail: false,
            },
            {
                id:nanoid(),
                name:"dog",
                isChosen:false,
                turn:false,
                money:1550,
                boardSpace: 1,
                property: [],
                isBankrupt: false,
                isInJail: false,
            },
            {
                id:nanoid(),
                name:"boat",
                isChosen:false,
                turn:false,
                money:1550,
                boardSpace: 1,
                property: [],
                isBankrupt: false,
                isInJail: false,
            },
            {
                id:nanoid(),
                name:"cat",
                isChosen:false,
                turn:false,
                money:1550,
                boardSpace: 1,
                property: [],
                isBankrupt: false,
                isInJail: false,
            },
        ]
    }
}